Added dependency to solve linux compilation error
Linux compilation shows this error on the node GYP process

    ../libuiohook/src/x11/input_hook.c:38:10: fatal error: X11/extensions/record.h: No such file or directory
       38 | #include <X11/extensions/record.h>

to solve it, the installation of the libxtst-dev library is required.

"fatal error: X11/extensions/record.h: No such file or directory. which was solved by installing libxtst-dev."